import React, { useState } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { toast } from 'react-toastify';
import { motion, AnimatePresence } from 'framer-motion';

// ── TERMS MODAL ──
function TermsModal({ onAccept, onDecline }) {
  const [scrolledToBottom, setScrolledToBottom] = useState(false);

  function handleScroll(e) {
    const el = e.target;
    const atBottom = el.scrollHeight - el.scrollTop <= el.clientHeight + 20;
    if (atBottom) setScrolledToBottom(true);
  }

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 z-50 flex items-center justify-center px-4"
      style={{ background: 'rgba(0,0,0,0.85)', backdropFilter: 'blur(6px)' }}
    >
      <motion.div
        initial={{ opacity: 0, scale: 0.92, y: 30 }}
        animate={{ opacity: 1, scale: 1, y: 0 }}
        exit={{ opacity: 0, scale: 0.95 }}
        transition={{ duration: 0.3 }}
        className="w-full max-w-2xl bg-gray-900 border border-white/10 rounded-3xl overflow-hidden shadow-2xl"
      >
        {/* Header */}
        <div className="px-8 py-5 border-b border-white/10 flex items-center gap-3">
          <div className="w-10 h-10 neuro-gradient rounded-xl flex items-center justify-center">
            <span className="text-white font-bold">📋</span>
          </div>
          <div>
            <h2 className="text-xl font-black text-white">Terms & Conditions</h2>
            <p className="text-xs text-gray-400">NeuroPulse AI — Please read carefully before registering</p>
          </div>
        </div>

        {/* Scrollable content */}
        <div
          onScroll={handleScroll}
          className="px-8 py-6 overflow-y-auto text-gray-300 text-sm leading-relaxed space-y-5"
          style={{ maxHeight: '52vh' }}
        >
          <section>
            <h3 className="text-white font-bold text-base mb-2">1. Medical Disclaimer</h3>
            <p>NeuroPulse AI provides <strong className="text-yellow-400">screening tools only</strong> and is <strong className="text-red-400">not a substitute for professional medical diagnosis</strong>. All results generated by this platform — including neurological risk scores for Parkinson's, Alzheimer's, Stroke, Multiple Sclerosis, and Cognitive Decline — are indicative and for awareness purposes only. You must consult a licensed medical professional for any health concerns or before making any medical decisions.</p>
          </section>

          <section>
            <h3 className="text-white font-bold text-base mb-2">2. Data Collection & Privacy</h3>
            <p>By registering, you agree that NeuroPulse AI may collect and process the following data:</p>
            <ul className="list-disc list-inside mt-2 space-y-1 text-gray-400">
              <li>Personal information (name, email, age, blood group, phone)</li>
              <li>Live webcam video frames for facial landmark analysis (processed locally in your browser — not stored)</li>
              <li>Test results and screening scores stored securely in our database</li>
              <li>Medical records and documents you voluntarily upload to MediPass</li>
            </ul>
            <p className="mt-2">Your data will never be sold to third parties. Webcam frames are processed entirely in your browser using MediaPipe and are <strong className="text-green-400">never transmitted to our servers</strong>.</p>
          </section>

          <section>
            <h3 className="text-white font-bold text-base mb-2">3. Camera & Microphone Access</h3>
            <p>Certain screening tests (Stroke Detection, MS Eye Tracking) require access to your device camera. By proceeding, you consent to granting camera permissions when prompted by your browser. You may revoke this permission at any time through your browser settings. Camera access is used solely for on-device analysis and no raw video is stored or transmitted.</p>
          </section>

          <section>
            <h3 className="text-white font-bold text-base mb-2">4. User Responsibilities</h3>
            <p>You agree to:</p>
            <ul className="list-disc list-inside mt-2 space-y-1 text-gray-400">
              <li>Provide accurate personal information during registration</li>
              <li>Keep your login credentials confidential</li>
              <li>Not use this platform for any fraudulent or unlawful purpose</li>
              <li>Not attempt to reverse-engineer or misuse the AI models</li>
              <li>Seek immediate medical attention in case of emergency rather than relying on this tool</li>
            </ul>
          </section>

          <section>
            <h3 className="text-white font-bold text-base mb-2">5. Accuracy & Limitations</h3>
            <p>AI-based neurological screening is an emerging field. NeuroPulse AI results may have false positives or false negatives. A high-risk score does <strong className="text-red-400">not</strong> confirm a diagnosis, and a low-risk score does <strong className="text-red-400">not</strong> rule out a condition. Always follow up with a qualified neurologist.</p>
          </section>

          <section>
            <h3 className="text-white font-bold text-base mb-2">6. Doctor Access to Records</h3>
            <p>If you use the MediPass feature, doctors you authorize (via QR code or direct access) will be able to view your health records and test results. You maintain full control over which doctors can access your data and can revoke access at any time from your dashboard.</p>
          </section>

          <section>
            <h3 className="text-white font-bold text-base mb-2">7. Intellectual Property</h3>
            <p>All content, algorithms, UI designs, and AI models within NeuroPulse AI are proprietary. You may not copy, distribute, or reproduce any part of this platform without express written permission from NeuroPulse AI.</p>
          </section>

          <section>
            <h3 className="text-white font-bold text-base mb-2">8. Changes to Terms</h3>
            <p>NeuroPulse AI reserves the right to update these Terms & Conditions at any time. Continued use of the platform after changes constitutes your acceptance of the new terms. We will notify registered users of significant changes via email.</p>
          </section>

          <section>
            <h3 className="text-white font-bold text-base mb-2">9. Governing Law</h3>
            <p>These terms are governed by and construed in accordance with applicable laws. Any disputes shall be resolved in the appropriate jurisdiction where NeuroPulse AI operates.</p>
          </section>

          <div className="py-2 text-center text-gray-500 text-xs">
            — End of Terms & Conditions —
          </div>
        </div>

        {/* Scroll hint */}
        {!scrolledToBottom && (
          <div className="px-8 py-2 bg-yellow-900/20 border-t border-yellow-500/20 text-center">
            <p className="text-yellow-400 text-xs">📜 Please scroll to the bottom to read all terms before accepting</p>
          </div>
        )}

        {/* Actions */}
        <div className="px-8 py-5 border-t border-white/10 flex gap-4">
          <button
            onClick={onDecline}
            className="flex-1 py-3 glass border border-white/20 rounded-xl font-semibold text-gray-300 hover:bg-white/10 transition"
          >
            ✕ Decline
          </button>
          <button
            onClick={onAccept}
            disabled={!scrolledToBottom}
            className={`flex-1 py-3 rounded-xl font-bold transition ${
              scrolledToBottom
                ? 'neuro-gradient text-white hover:opacity-90'
                : 'bg-gray-700 text-gray-500 cursor-not-allowed'
            }`}
          >
            {scrolledToBottom ? '✓ I Agree & Continue' : '↓ Scroll to Accept'}
          </button>
        </div>
      </motion.div>
    </motion.div>
  );
}

// ── REGISTER PAGE ──
export default function Register() {
  const [formData, setFormData] = useState({
    name: '', email: '', password: '', confirmPassword: '',
    role: 'patient', age: '', bloodGroup: '', phone: '',
  });
  const [loading, setLoading]           = useState(false);
  const [showTerms, setShowTerms]       = useState(false);
  const [termsAccepted, setTermsAccepted] = useState(false);
  const { register } = useAuth();
  const navigate = useNavigate();

  function handleChange(e) {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  }

  function validateForm() {
    if (!formData.name.trim())  { toast.error('Please enter your full name'); return false; }
    if (!formData.email.trim()) { toast.error('Please enter your email'); return false; }
    if (formData.password.length < 6) { toast.error('Password must be at least 6 characters'); return false; }
    if (formData.password !== formData.confirmPassword) { toast.error('Passwords do not match'); return false; }
    return true;
  }

  function handleSubmitClick(e) {
    e.preventDefault();
    if (!validateForm()) return;
    if (!termsAccepted) {
      setShowTerms(true);
      return;
    }
    doRegister();
  }

  function handleTermsAccept() {
    setTermsAccepted(true);
    setShowTerms(false);
    doRegister();
  }

  function handleTermsDecline() {
    setShowTerms(false);
    toast.error('You must accept the Terms & Conditions to register.');
  }

  async function doRegister() {
    setLoading(true);
    try {
      await register(formData.email, formData.password, formData.name, formData.role);
      toast.success('Account created successfully!');
      navigate(formData.role === 'doctor' ? '/doctor/dashboard' : '/patient/dashboard');
    } catch (error) {
      toast.error(error.message);
    }
    setLoading(false);
  }

  return (
    <>
      <AnimatePresence>
        {showTerms && (
          <TermsModal onAccept={handleTermsAccept} onDecline={handleTermsDecline} />
        )}
      </AnimatePresence>

      <div className="min-h-screen bg-gray-950 flex items-center justify-center px-6 py-12">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="w-full max-w-lg"
        >
          {/* Logo */}
          <div className="text-center mb-8">
            <div className="w-16 h-16 neuro-gradient rounded-2xl flex items-center justify-center mx-auto mb-4">
              <span className="text-white font-black text-2xl">N</span>
            </div>
            <h1 className="text-3xl font-black gradient-text">NeuroPulse</h1>
            <p className="text-gray-400 mt-2">Create your account to get started</p>
          </div>

          {/* Form card */}
          <div className="glass rounded-3xl p-8">

            {/* Role toggle */}
            <div className="flex gap-4 mb-6">
              {['patient', 'doctor'].map(role => (
                <button key={role} type="button"
                  onClick={() => setFormData({ ...formData, role })}
                  className={`flex-1 py-3 rounded-xl font-semibold capitalize transition ${
                    formData.role === role ? 'neuro-gradient text-white' : 'glass text-gray-400 hover:text-white'
                  }`}
                >
                  {role === 'patient' ? '🧑‍⚕️ Patient' : '👨‍⚕️ Doctor'}
                </button>
              ))}
            </div>

            <form onSubmit={handleSubmitClick} className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-300 mb-2">Full Name</label>
                  <input type="text" name="name" value={formData.name} onChange={handleChange} required
                    className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3 text-white placeholder-gray-500 focus:outline-none focus:border-purple-500 transition"
                    placeholder="John Doe" />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-300 mb-2">Phone Number</label>
                  <input type="tel" name="phone" value={formData.phone} onChange={handleChange}
                    className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3 text-white placeholder-gray-500 focus:outline-none focus:border-purple-500 transition"
                    placeholder="+91 9999999999" />
                </div>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Email Address</label>
                <input type="email" name="email" value={formData.email} onChange={handleChange} required
                  className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3 text-white placeholder-gray-500 focus:outline-none focus:border-purple-500 transition"
                  placeholder="you@example.com" />
              </div>

              {formData.role === 'patient' && (
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-300 mb-2">Age</label>
                    <input type="number" name="age" value={formData.age} onChange={handleChange}
                      className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3 text-white placeholder-gray-500 focus:outline-none focus:border-purple-500 transition"
                      placeholder="25" min="1" max="120" />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-gray-300 mb-2">Blood Group</label>
                    <select name="bloodGroup" value={formData.bloodGroup} onChange={handleChange}
                      className="w-full bg-gray-900 border border-white/10 rounded-xl px-4 py-3 text-white focus:outline-none focus:border-purple-500 transition">
                      <option value="">Select</option>
                      {['A+','A-','B+','B-','AB+','AB-','O+','O-'].map(bg => (
                        <option key={bg} value={bg}>{bg}</option>
                      ))}
                    </select>
                  </div>
                </div>
              )}

              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Password</label>
                <input type="password" name="password" value={formData.password} onChange={handleChange} required
                  className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3 text-white placeholder-gray-500 focus:outline-none focus:border-purple-500 transition"
                  placeholder="Min. 6 characters" />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-300 mb-2">Confirm Password</label>
                <input type="password" name="confirmPassword" value={formData.confirmPassword} onChange={handleChange} required
                  className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3 text-white placeholder-gray-500 focus:outline-none focus:border-purple-500 transition"
                  placeholder="••••••••" />
              </div>

              {/* Terms checkbox */}
              <div className={`flex items-start gap-3 p-4 rounded-xl border transition ${
                termsAccepted ? 'border-green-500/40 bg-green-900/10' : 'border-white/10 bg-white/5'
              }`}>
                <input
                  type="checkbox"
                  id="terms"
                  checked={termsAccepted}
                  onChange={() => {
                    if (!termsAccepted) { setShowTerms(true); }
                    else { setTermsAccepted(false); }
                  }}
                  className="mt-0.5 w-4 h-4 accent-purple-500 cursor-pointer flex-shrink-0"
                />
                <label htmlFor="terms" className="text-sm text-gray-300 cursor-pointer leading-relaxed">
                  I have read and agree to the{' '}
                  <button type="button" onClick={() => setShowTerms(true)}
                    className="text-purple-400 hover:text-purple-300 font-semibold underline underline-offset-2">
                    Terms & Conditions
                  </button>
                  {' '}including the Medical Disclaimer and Privacy Policy.
                  {termsAccepted && <span className="ml-2 text-green-400 font-semibold">✓ Accepted</span>}
                </label>
              </div>

              <button
                type="submit"
                disabled={loading}
                className="w-full py-3 neuro-gradient rounded-xl font-bold text-lg hover:opacity-90 transition disabled:opacity-50 mt-2 relative"
              >
                {loading ? 'Creating Account...' : (
                  !termsAccepted
                    ? '📋 Review Terms & Register →'
                    : 'Create Account →'
                )}
              </button>
            </form>

            <p className="text-center text-gray-400 mt-6">
              Already have an account?{' '}
              <Link to="/login" className="text-purple-400 hover:text-purple-300 font-semibold">Login here</Link>
            </p>
          </div>
        </motion.div>
      </div>
    </>
  );
}
